### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by DaniLucky06** [Bithack/principia#103]
I uploaded the windows file to VirusTotal, because Windows told me it could be harmful, and a Virus has been found. What should I do, is it a false positive?
![image](https://user-images.githubusercontent.com/121113019/228876455-e79a55f0-fc86-4614-80a7-ed209a1bb6c9.png)

**Comment by rollerozxa** [comment]
Principia is not a virus and is safe to run, but that's of course what I would say considering I compiled the build. Generally though if only one AV engine detects something it's usually a false positive.

If you want to be extra sure you can open the installer executable like a zip archive using 7-Zip, and extract the game manually. Then zip up principia.exe and accompanying DLL files and upload to VirusTotal. At least for me, Trapmine doesn't detect it anymore when I do that. You can play the game portably that way too, but keep in mind community site level buttons won't work since you'll be missing registry keys for protocol association (see [Principia URI Protocol](https://principia-web.se/wiki/Principia_Protocol#platform-implementation)).

**Comment by DaniLucky06** [comment]
Thank you :D I already scanned it with another antivirus before reading this, and installed it! Thanks! 
Btw, thank you for re-taking principia up after all this time! I had it installed on the phone for ages and never uninstalled it!

**Comment by rollerozxa** [comment]
No problem, thank you for sticking around. :heart:
