### ISSUE TITLE
Error: SDL C/Java version mismatch (expected 2.30.5 got 2.30.3)

### ISSUE THREAD

**Issue by ManDay** [Bithack/principia#177]
Since the [latest update](https://principia-web.se/news/16) on F-Droid, the app fails to start with a prompt saying

> SDL Error
> An error occured while trying to start the application. Please try again and/or reinstall
>
> Error: SDL C/Java version mismatch (expected 2.30.5 got 2.30.3)

Reinstallation, clearing user data has no effect.

Version 2024.07.12 (F-Droid), DivestOS-20

**Comment by rollerozxa** [comment]
F-Droid built 2024.07.12 with an old version of our Android dependencies [despite us having tagged the correct version to use](https://github.com/principia-game/android-deps/tree/2024.07.12) and apparently nobody noticed until it has gone live. You'll have to report this up to F-Droid to have them rebuild the version.

**Comment by ManDay** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/3317

**Comment by linsui** [comment]
> even if they are tagged the same way as the main repo

If it's guaranteed to be tagged in the same way, we can update it automatically. Of course, git submodule is preferred.

**Comment by rollerozxa** [comment]
Ah, I see. Submodule would be best yeah.

I've tagged a new release [2024.07.12-fdroid](https://github.com/Bithack/principia/releases/tag/2024.07.12-fdroid) that includes the android-deps repository as a submodule at `build-android/principia/deps-src`. So you should be able to edit the F-Droid buildscript to go there when building the native dependencies instead of the srclib for this release.

**Comment by linsui** [comment]
Thanks! I guess the build steps are not changed and I just need to use a different path, right?

**Comment by rollerozxa** [comment]
Yeah.

**Comment by linsui** [comment]
Updated, thanks!
