### ISSUE TITLE
Fluid Limit

### ISSUE THREAD

**Issue by wereretot** [Bithack/principia#67]
Increase fluid limit as it is too low for higher-end hardware.

**Comment by Blue-Beaker** [comment]
Fluid limit should no longer be hardcoded but become a level setting, allowing levels to increase fluid limits when needed, while keeping old levels using old limits as default to not break things.

**Comment by coolguy284** [comment]
On Windows 10, modifying the fluid limit to be much greater works, but the extra fluid particles don't render for some reason (they still interact with objects though). This behavior is similar to something I remember messing with a while back, Google's LiquidFun extension of Box2D (to see what I mean go to https://google.github.io/liquidfun/ and change it from "Dam Break" to "Drawing Particles" and drag the mouse around the walls a bunch). Perhaps since Principia uses Box2D it has the same issue?

**Comment by griffi-gh** [comment]
https://github.com/Bithack/principia/commit/5bc55aa0f5dc85e5df6f7d8f2a0b89bb1430a189 closes this issue
